Total Checked In =
COUNTROWS('SRP Patient Flow Tracker')

Completed =
CALCULATE(
    COUNTROWS('SRP Patient Flow Tracker'),
    'SRP Patient Flow Tracker'[Current Step] = "Complete"
)

Waiting Provider =
CALCULATE(
    COUNTROWS('SRP Patient Flow Tracker'),
    'SRP Patient Flow Tracker'[Current Step] = "Ready for Provider"
)

Primary Care Referrals =
CALCULATE(
    COUNTROWS('SRP Patient Flow Tracker'),
    'SRP Patient Flow Tracker'[Primary Care Referral] = TRUE()
)

Same Day Completion Rate =
DIVIDE([Completed], [Total Checked In], 0)

Open Cases =
CALCULATE(
    COUNTROWS('SRP Patient Flow Tracker'),
    FILTER(
        'SRP Patient Flow Tracker',
        NOT('SRP Patient Flow Tracker'[Current Step] IN { "Complete", "Primary Care Referral" })
    )
)

Average Time in Clinic Minutes =
AVERAGEX(
    FILTER(
        'SRP Patient Flow Tracker',
        NOT ISBLANK('SRP Patient Flow Tracker'[Completed Time])
    ),
    DATEDIFF(
        'SRP Patient Flow Tracker'[Arrival Time],
        'SRP Patient Flow Tracker'[Completed Time],
        MINUTE
    )
)

Provider Wait Minutes =
VAR Arrival = SELECTEDVALUE('SRP Patient Flow Tracker'[Arrival Time])
VAR ProviderStart = SELECTEDVALUE('SRP Patient Flow Tracker'[Provider Start Time])
VAR CurrentStep = SELECTEDVALUE('SRP Patient Flow Tracker'[Current Step])
RETURN
IF(
    CurrentStep = "Ready for Provider",
    DATEDIFF(Arrival, NOW(), MINUTE),
    IF(NOT ISBLANK(ProviderStart), DATEDIFF(Arrival, ProviderStart, MINUTE))
)

Provider Wait Status =
VAR MinutesWaiting = [Provider Wait Minutes]
RETURN
SWITCH(
    TRUE(),
    ISBLANK(MinutesWaiting), BLANK(),
    MinutesWaiting < 10, "Green",
    MinutesWaiting <= 20, "Yellow",
    "Red"
)

Completed Today =
CALCULATE(
    [Completed],
    FILTER(
        'SRP Patient Flow Tracker',
        NOT ISBLANK('SRP Patient Flow Tracker'[Completed Time])
            && INT('SRP Patient Flow Tracker'[Completed Time]) = TODAY()
    )
)

Completion Rate Label =
FORMAT([Same Day Completion Rate], "0.0%")
